name: deployment

on:
  workflow_dispatch:

env:
  HOST: cassini.cs.kent.edu
  USER: whackamole
  TARGET: whackamole@cassini.cs.kent.edu
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no whackamole@cassini.cs.kent.edu
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  deploy_to_cassini:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Get the repo code
        uses: actions/checkout@v2
        with: 
          repository: shahriar-nehal/SWE
      - name: Look at the files
        run: |
          echo $ ls -la 
          ls -la 
          echo $ pwd
          pwd
      - name: Ping the server
        run: |
          $RUN 'ls -la'
          echo "hello" >hello.txt
          $COPY hello.txt $TARGET:/home/whackamole
